[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  included_files = ["certs/*"]

[functions.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."api"]
  node_bundler = "esbuild"
